repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^archive/
      - id: end-of-file-fixer
        exclude: ^archive/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^archive/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^archive/
      - id: ruff-format
        exclude: ^archive/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        exclude: ^(archive/|tests/)
        additional_dependencies:
          - types-click
          - types-PyYAML
